export const medicalConditions = [
  "I'd rather not say",
  "Celiac Disease",
  "Gluten Sensitivity",
  "Gluten Intolerance",
  "A Wheat Allergy",
  "Crohn's Disease",
  "Hashimoto's Disease",
  "IBS",
  "FODMAP Intolerance",
  "Eosinophilic Esophagitis",
  "FPIES",
  "Dermatitis Herpetiformis",
  "Sjogren's Syndrome",
  "Lupus",
  "Gluten Ataxia",
  "Lymphocytic Esophagitis",
  "Lyme Disease",
  "Graves Disease",
  "Ulcerative Colitis",
  "Endometriosis",
  "Auto-Brewery Syndrome",
  "Multiple Sclerosis",
  "Fibromyalgia",
  "Rheumatoid Arthritis",
  "MTHFR",
  "MCAS",
  "Other",
];

export const questions = [
  {
    q: "What brought you here today?",
    key: "reason" as const,
    type: "checkbox" as const,
    options: [
      { title: "Eating out safely", sub: "I want help navigating restaurant menus" },
      { title: "Traveling with celiac", sub: "I need support dining in unfamiliar places" },
      { title: "I'm newly diagnosed", sub: "I want to learn what's safe" },
      { title: "Helping someone I know", sub: "A friend or family member has celiac" },
    ],
  },
  {
    q: "I'm gluten free because:",
    key: "condition" as const,
    type: "dropdown" as const,
    textInputLabel: "Other dietary preferences",
    textInputKey: "otherDietaryPreferences" as const,
  },
  {
    q: "Are you symptomatic?",
    key: "symptomatic" as const,
    type: "radio" as const,
    options: [
      { title: "Rarely", sub: "" },
      { title: "Sometimes", sub: "" },
      { title: "Always", sub: "" },
      { title: "Severely", sub: "" },
    ],
    textInputLabel: "Additional comments",
    textInputKey: "symptomNotes" as const,
  },
  {
    q: "How strictly do you avoid cross-contact?",
    key: "crossContamination" as const,
    type: "radio" as const,
    options: [
      { title: "I'd rather not say", sub: "" },
      { title: "Not concerned", sub: "" },
      { title: "Avoid if possible", sub: "" },
      { title: "Pretty strict", sub: "" },
      { title: "Very strict", sub: "" },
    ],
    textInputLabel: "Additional comments",
    textInputKey: "crossContaminationNotes" as const,
  },
];
